--- # create service for deployment
- hosts: kubernetes
  user: root
  become: yes
  connection: ssh

  tasks:
  - name: copy a service file to Kubernetes
    copy: src=/home/ec2-user/kubernetes/click2cloud-service.yml dest=/root/
    
  - name: create a service
    command: kubectl apply -f /home/ec2-user/playbooks/click2cloud-service.yml
